language: php
dist: trusty
sudo: required

matrix:
  include:
    - php: 5.6
      env: DB=mysqli
    - php: 5.6
      # phpBB's MariaDB stuff only seems to be set up for Travis's deprecated Precise
      # environment. I'm okay with that, especially as I can't think of anything I
      # could do to make things not work on MariaDB when they work on MySQL...
      dist: precise    
      env: DB=mariadb
    - php: 5.6
      env: DB=postgres
    - php: 5.6
      env: DB=sqlite3
    - php: 7.0
      env: DB=mysqli
    - php: 7.1
      env: DB=mysqli
    - php: hhvm
      env: DB=mysqli
  allow_failures:
#    - php: hhvm
  fast_finish: true

env:
  global:
    - EXTNAME="gothick/akismet"  # CHANGE name of the extension HERE
    - SNIFF="1"            # Should we run code sniffer on your code?
    - IMAGE_ICC="1"        # Should we run icc profile sniffer on your images?
    - EPV="1"              # Should we run EPV (Extension Pre Validator) on your code?
    - PHPBB_BRANCH="3.2.x"

branches:
  only:
    - master
    - /^\d+(\.\d+)?\.x$/
    - registration

install:
  - composer install --no-interaction --prefer-source
  - travis/prepare-phpbb.sh $EXTNAME $PHPBB_BRANCH
  - cd ../../phpBB3
  - travis/prepare-extension.sh $EXTNAME $PHPBB_BRANCH
  - travis/setup-phpbb.sh $DB $TRAVIS_PHP_VERSION
# Idea nicked from https://github.com/AlfredoRamos/phpbb-ext-imgur. Looks like the EPV clashes with sami/sami requirements, so remove it first.
  - sh -c "if [ '$EPV' != '0' -a '$TRAVIS_PHP_VERSION' = '5.6' -a '$DB' = 'mysqli' ]; then cd phpBB; composer remove sami/sami --update-with-dependencies --dev --no-interaction; composer require phpbb/epv:dev-master --dev --no-interaction --ignore-platform-reqs; cd ../; fi"

before_script:
  - travis/setup-database.sh $DB $TRAVIS_PHP_VERSION

script:
  - sh -c "if [ '$SNIFF' != '0' ]; then travis/ext-sniff.sh $DB $TRAVIS_PHP_VERSION $EXTNAME; fi"
  - sh -c "if [ '$IMAGE_ICC' != '0' ]; then travis/check-image-icc-profiles.sh $DB $TRAVIS_PHP_VERSION; fi"
  - phpBB/vendor/bin/phpunit --configuration phpBB/ext/$EXTNAME/travis/phpunit-$DB-travis.xml --bootstrap phpBB/ext/$EXTNAME/tests/bootstrap.php
  - sh -c "if [ '$EPV' != '0' -a '$TRAVIS_PHP_VERSION' = '5.6' -a '$DB' = 'mysqli' ]; then phpBB/vendor/bin/EPV.php run --dir='phpBB/ext/$EXTNAME/'; fi"
